const nodemailer = require('nodemailer');
const financialService = require('./financialService');
const Vehicle = require('../models/Vehicle');
const Rental = require('../models/Rental');
const Transaction = require('../models/Transaction');
const moment = require('moment');

// Email transporter configuration
const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: process.env.EMAIL_PORT,
    secure: false,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS
    }
  });
};

// Generate weekly report
const generateWeeklyReport = async () => {
  try {
    const now = new Date();
    const weekStart = moment(now).startOf('week').toDate();
    const weekEnd = moment(now).endOf('week').toDate();

    // Get financial data
    const netIncome = await financialService.calculateMonthlyNetIncome(now);
    const utilization = await financialService.calculateFleetUtilizationRate();
    const racd = await financialService.calculateRACD(now);

    // Get vehicle performance
    const vehicles = await Vehicle.find({ availability_status: { $in: ['In-Fleet', 'Rented'] } });
    const vehiclePerformances = await Promise.all(
      vehicles.slice(0, 10).map(v => financialService.getVehiclePerformance(v._id, now))
    );

    // Get weekly transactions summary
    const transactions = await Transaction.find({
      date: { $gte: weekStart, $lte: weekEnd },
      status: 'Confirmed'
    });

    const revenue = transactions
      .filter(t => t.type === 'C2B')
      .reduce((sum, t) => sum + t.amount, 0);

    const expenses = transactions
      .filter(t => ['B2C Owner Payout', 'B2C Driver Salary', 'Cost Allocation'].includes(t.type))
      .reduce((sum, t) => sum + t.amount, 0);

    // Generate report HTML
    const reportHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .header { background-color: #2c3e50; color: white; padding: 20px; text-align: center; }
          .content { padding: 20px; }
          .metric { background-color: #f4f4f4; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; }
          .metric h3 { margin-top: 0; color: #2c3e50; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
          th { background-color: #3498db; color: white; }
          .footer { text-align: center; padding: 20px; color: #777; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>THE RESSEY TOURS AND CAR HIRE</h1>
          <h2>Weekly Performance Report</h2>
          <p>Week of ${moment(weekStart).format('MMMM DD, YYYY')} - ${moment(weekEnd).format('MMMM DD, YYYY')}</p>
        </div>
        <div class="content">
          <div class="metric">
            <h3>Financial Summary</h3>
            <p><strong>Weekly Revenue:</strong> KES ${revenue.toLocaleString()}</p>
            <p><strong>Weekly Expenses:</strong> KES ${expenses.toLocaleString()}</p>
            <p><strong>Net Income (Month-to-Date):</strong> KES ${netIncome.net_income.toLocaleString()}</p>
            <p><strong>Gross Profit Margin:</strong> ${netIncome.gross_profit_margin}%</p>
            <p><strong>Net Profit Margin:</strong> ${netIncome.net_profit_margin}%</p>
          </div>

          <div class="metric">
            <h3>Fleet Performance</h3>
            <p><strong>Fleet Utilization Rate:</strong> ${utilization.utilization_rate}%</p>
            <p><strong>Total Fleet:</strong> ${utilization.total_fleet} vehicles</p>
            <p><strong>Currently Rented:</strong> ${utilization.rented_vehicles} vehicles</p>
            <p><strong>Revenue Per Available Car-Day (RACD):</strong> KES ${racd.racd}</p>
          </div>

          <div class="metric">
            <h3>Top Performing Vehicles</h3>
            <table>
              <thead>
                <tr>
                  <th>Vehicle</th>
                  <th>Revenue</th>
                  <th>Hired Days</th>
                  <th>GCCM</th>
                </tr>
              </thead>
              <tbody>
                ${vehiclePerformances.map(v => `
                  <tr>
                    <td>${v.vehicle_model}</td>
                    <td>KES ${v.revenue.toLocaleString()}</td>
                    <td>${v.hired_days}</td>
                    <td>KES ${v.gccm.toLocaleString()}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>
        </div>
        <div class="footer">
          <p>This is an automated report generated by THE RESSEY TOURS CRMS</p>
          <p>Generated on ${moment(now).format('MMMM DD, YYYY [at] HH:mm')}</p>
        </div>
      </body>
      </html>
    `;

    // Send email to Director
    const transporter = createTransporter();
    const directorEmail = process.env.DIRECTOR_EMAIL;

    if (directorEmail) {
      await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: directorEmail,
        subject: `Weekly Performance Report - ${moment(now).format('MMMM DD, YYYY')}`,
        html: reportHTML
      });

      console.log(`Weekly report sent to ${directorEmail}`);
    }

    return {
      success: true,
      report: {
        week_start: weekStart,
        week_end: weekEnd,
        financial_summary: {
          weekly_revenue: revenue,
          weekly_expenses: expenses,
          net_income: netIncome.net_income
        },
        fleet_performance: {
          utilization_rate: utilization.utilization_rate,
          racd: racd.racd
        }
      }
    };
  } catch (error) {
    console.error('Error generating weekly report:', error);
    throw error;
  }
};

module.exports = {
  generateWeeklyReport
};

